; This initialize the custom save data variables to their initial values. Note that these values get changed based on the seed.

LAB_NEW_SAVE_CUSTOM_VARIABLES:
	stmdb sp!,{r3,lr}
	bl 0x0205ac0c
	bl FUN_GET_CUSTOM_SAVE_CONTEXT_ADDR
	mov r3,r0
	ldr r1,[@SV_DAT_MOVEMENT_SPEED_PTR]
	ldrb r0,[r1]
	; todo
	; Level Cap
	ldr r1,[@SV_DAT_LEVEL_CAP_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_LEVEL_CAP]
	; Floor Limit
	ldr r1,[@SV_DAT_FLOOR_LIMIT_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_FLOOR_LIMIT]
	; Experience Modifier
	ldr r0,[SV_DAT_EXPERIENCE_MODIFIER]
	
	; Class Available
	; Landsknecht
	ldr r1,[@SV_DAT_CLASS_LANDSKNECHT_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_CLASS_UNLOCK+0]
	; Survivalist
	ldr r1,[@SV_DAT_CLASS_SURVIVALIST_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_CLASS_UNLOCK+1]
	; Protector
	ldr r1,[@SV_DAT_CLASS_PROTECTOR_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_CLASS_UNLOCK+2]
	; Dark Hunter
	ldr r1,[@SV_DAT_CLASS_DARK_HUNTER_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_CLASS_UNLOCK+3]
	; Medic
	ldr r1,[@SV_DAT_CLASS_MEDIC_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_CLASS_UNLOCK+4]
	; Alchemist
	ldr r1,[@SV_DAT_CLASS_ALCHEMIST_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_CLASS_UNLOCK+5]
	; Troubadour
	ldr r1,[@SV_DAT_CLASS_TROUDABOUR_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_CLASS_UNLOCK+6]
	; Ronin
	ldr r1,[@SV_DAT_CLASS_RONIN_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_CLASS_UNLOCK+7]
	; Hexer
	ldr r1,[@SV_DAT_CLASS_HEXER_PTR]
	ldrb r0,[r1]
	strb r0,[r3,SC_CLASS_UNLOCK+8]
	
	; Skill Available (Warning, the memory order of these is different to Class unlocks)
	; Landsknecht
	ldr r0,[SV_DAT_SKILL_LANDSKNECHT]
	str r0,[r3,SC_SKILL_UNLOCK_OFFSET+(SC_SKILL_UNLOCK_CLASS_SIZE*0)]
	; Survivalist
	ldr r0,[SV_DAT_SKILL_SURVIVALIST]
	str r0,[r3,SC_SKILL_UNLOCK_OFFSET+(SC_SKILL_UNLOCK_CLASS_SIZE*1)]
	; Protector
	ldr r0,[SV_DAT_SKILL_PROTECTOR]
	str r0,[r3,SC_SKILL_UNLOCK_OFFSET+(SC_SKILL_UNLOCK_CLASS_SIZE*2)]
	; Dark Hunter
	ldr r0,[SV_DAT_SKILL_DARK_HUNTER]
	str r0,[r3,SC_SKILL_UNLOCK_OFFSET+(SC_SKILL_UNLOCK_CLASS_SIZE*3)]
	; Ronin
	ldr r0,[SV_DAT_SKILL_RONIN]
	str r0,[r3,SC_SKILL_UNLOCK_OFFSET+(SC_SKILL_UNLOCK_CLASS_SIZE*4)]
	; Medic
	ldr r0,[SV_DAT_SKILL_MEDIC]
	str r0,[r3,SC_SKILL_UNLOCK_OFFSET+(SC_SKILL_UNLOCK_CLASS_SIZE*5)]
	; Alchemist
	ldr r0,[SV_DAT_SKILL_ALCHEMIST]
	str r0,[r3,SC_SKILL_UNLOCK_OFFSET+(SC_SKILL_UNLOCK_CLASS_SIZE*6)]
	; Troubadour
	ldr r0,[SV_DAT_SKILL_TROUDABOUR]
	str r0,[r3,SC_SKILL_UNLOCK_OFFSET+(SC_SKILL_UNLOCK_CLASS_SIZE*7)]
	; Hexer
	ldr r0,[SV_DAT_SKILL_HEXER]
	str r0,[r3,SC_SKILL_UNLOCK_OFFSET+(SC_SKILL_UNLOCK_CLASS_SIZE*8)]
	
	ldmia sp!,{r3,pc}
	
@SV_DAT_MOVEMENT_SPEED_PTR:
	.d32 SV_DAT_MOVEMENT_SPEED

@SV_DAT_LEVEL_CAP_PTR:
	.d32 SV_DAT_LEVEL_CAP

@SV_DAT_FLOOR_LIMIT_PTR:
	.d32 SV_DAT_FLOOR_LIMIT

@SV_DAT_CLASS_LANDSKNECHT_PTR:	
	.d32 SV_DAT_CLASS_LANDSKNECHT
@SV_DAT_CLASS_SURVIVALIST_PTR:	
	.d32 SV_DAT_CLASS_SURVIVALIST
@SV_DAT_CLASS_PROTECTOR_PTR:	
	.d32 SV_DAT_CLASS_PROTECTOR
@SV_DAT_CLASS_DARK_HUNTER_PTR:	
	.d32 SV_DAT_CLASS_DARK_HUNTER
@SV_DAT_CLASS_MEDIC_PTR:	
	.d32 SV_DAT_CLASS_MEDIC
@SV_DAT_CLASS_ALCHEMIST_PTR:	
	.d32 SV_DAT_CLASS_ALCHEMIST
@SV_DAT_CLASS_TROUDABOUR_PTR:	
	.d32 SV_DAT_CLASS_TROUDABOUR
@SV_DAT_CLASS_RONIN_PTR:	
	.d32 SV_DAT_CLASS_RONIN
@SV_DAT_CLASS_HEXER_PTR:	
	.d32 SV_DAT_CLASS_HEXER

; Not necessary for now.
;@SV_DAT_SKILL_LANDSKNECHT_PTR:
;	.d32 SV_DAT_SKILL_LANDSKNECHT
;@SV_DAT_SKILL_SURVIVALIST_PTR:
;	.d32 SV_DAT_SKILL_SURVIVALIST
;@SV_DAT_SKILL_PROTECTOR_PTR:
;	.d32 SV_DAT_SKILL_PROTECTOR
;@SV_DAT_SKILL_DARK_HUNTER_PTR:
;	.d32 SV_DAT_SKILL_DARK_HUNTER
;@SV_DAT_SKILL_MEDIC_PTR:
;	.d32 SV_DAT_SKILL_MEDIC
;@SV_DAT_SKILL_ALCHEMIST_PTR:
;	.d32 SV_DAT_SKILL_ALCHEMIST
;@SV_DAT_SKILL_TROUDABOUR_PTR:
;	.d32 SV_DAT_SKILL_TROUDABOUR
;@SV_DAT_SKILL_RONIN_PTR:
;	.d32 SV_DAT_SKILL_RONIN
;@SV_DAT_SKILL_HEXER_PTR:
;	.d32 SV_DAT_SKILL_HEXER