; As of now, the free space in the save context is known to be a maximum of 0x3FC

SC_LEVEL_CAP equ 0x00
SC_FLOOR_LIMIT equ 0x01

; For AP synchronization.
SC_LAST_RECEIVED_ITEM_INDEX equ 0x04
SC_LAST_RECEIVED_INVENTORY_ITEM_INDEX equ 0x08

;0x10
SC_CLASS_UNLOCK equ 0x10

;0x20
SC_SKILL_UNLOCK_OFFSET equ 0x20
SC_SKILL_UNLOCK_CLASS_SIZE equ 0x04
; 0x44

SC_SYNCHRONIZATION_SAFEGUARD equ 0x44

SC_MONEY_RECEPTION_OFFSET equ 0x48 ; Not implemented

SC_ITEM_RECEPTION_OFFSET equ 0x4C
SC_ITEM_RECEPTION_ITEM_COUNT equ 0x14 ; 20 items
SC_ITEM_RECEPTION_ARRAY_SIZE equ 0x28 ; 20 items